export const productActionsTypes = {
  REQUEST: "REQUESTPRODUCTS",
  SUCCESS: "SUCCESSPRODUCTS",
  FAILURE: "FAILUREPRODUCTS",
};

export const categoriesActionsTypes = {
  SUCCESS: "SUCCESSCATEGOIES",
};
export const cartActionsTypes = {
  ADDTOCART: "ADDTOCART",
  REMOVEFROMCART:"REMOVEFROMCART",
  UPDATEQUANTITY:"UPDATEQUANTITY"
};
